# Generated by Django 2.2.7 on 2019-11-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20191110_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images_folder/None/no-img.jpg', upload_to='images_folder/'),
        ),
    ]
